/**
 * 电商助手 Chrome Extension - Content Script v3.1
 */
(function() {
  'use strict';
  function detect(){var h=location.hostname;if(h.includes('1688'))return '1688';if(h.includes('yangkeduo')||h.includes('pinduoduo'))return 'pinduoduo';if(h.includes('jd'))return 'jd';if(h.includes('tmall'))return 'tmall';if(h.includes('taobao'))return 'taobao';return 'unknown';}
  function first(sels){for(var i=0;i<sels.length;i++){var e=document.querySelector(sels[i]);if(e)return e;}return null;}
  function all(sels){for(var i=0;i<sels.length;i++){var es=document.querySelectorAll(sels[i]);if(es.length)return es;}return [];}
  function cleanUrl(u){return (u||'').replace(/_\d+x\d+\.\w+/,'').replace(/\?.*/,'').trim();}
  var PS={'1688':{title:['.title-text h1','.ma-title','h1.title'],price:['.price-value','.ma-ref-price'],images:['.main-image img','.vertical-img img'],attrs:['.product-attr-list li','.attr-list li']},'taobao':{title:['.tb-item-title h1','h1[data-spm]'],price:['.tb-price span','#J_StrPrice .tm-price'],images:['#J_ImgBooth','.tb-gallery img'],attrs:['.attributes li','#J_AttrList li']},'tmall':{title:['.ItemHeader--title--eUbQa5jP','h1.tb-item-title'],price:['.tm-price'],images:['#J_ImgBooth','.tb-gallery img'],attrs:['.attributes li']},'pinduoduo':{title:['.goods-title','.product-title'],price:['.goods-price','.price'],images:['.goods-img img','.gallery img'],attrs:[]},'jd':{title:['.p-name','#name h1'],price:['.p-price','#jdPrice .price'],images:['#spec-img','.preview-img img'],attrs:['.p-parameter li']}};
  function capture(){var p=detect(),s=PS[p]||{},d={title:'',price:0,images:[],skus:[],skuCount:1,attributes:{},shopName:'',soldCount:0,source:p,sourceUrl:location.href,capturedAt:new Date().toISOString()};var t=first(s.title||[]);if(t)d.title=t.textContent?.trim()||'';var pe=first(s.price||[]);d.price=parseFloat((pe?.textContent?.trim()||'0').replace(/[^\d.]/g,''))||0;var imgs=all(s.images||[]);d.images=[];for(var i=0;i<imgs.length;i++){var u=cleanUrl(imgs[i].src||imgs[i]['data-src']);if(u&&u.length>20&&!u.includes('data:'))d.images.push(u);}d.images=d.images.slice(0,15);if(p==='taobao'||p==='tmall'){var mi=document.querySelector('#J_ImgBooth,.tb-gallery img');if(mi){var mu=cleanUrl(mi.src||mi['data-src']);if(mu&&d.images.indexOf(mu)===-1)d.images.unshift(mu);}}var attrs=all(s.attrs||[]);for(var j=0;j<attrs.length;j++){var txt=attrs[j].textContent?.trim();if(txt&&(txt.includes(':')||txt.includes('：'))){var parts=txt.split(/[：:]/);if(parts[0]?.trim())d.attributes[parts[0].trim()]=parts.slice(1).join(':').trim();}}return d;}
  function fillForm(data){var r={filled:[],failed:[]};var sels=['input[placeholder*="标题"]','input[name*="title"]','textarea[name*="title"]'];for(var i=0;i<sels.length;i++){var el=document.querySelector(sels[i]);if(el&&!el.disabled){el.value=data.title||'';el.dispatchEvent(new Event('input',{bubbles:true}));r.filled.push('title');break;}}var ps=['input[placeholder*="价格"]','input[name*="price"]'];for(var j=0;j<ps.length;j++){var el2=document.querySelector(ps[j]);if(el2&&!el2.disabled){el2.value=data.price||'';el2.dispatchEvent(new Event('input',{bubbles:true}));r.filled.push('price');break;}}return r;}
  function addBtn(){if(document.getElementById('ecomassist-btn'))return;var btn=document.createElement('div');btn.id='ecomassist-btn';btn.innerHTML='<svg width="24" height="24" viewBox="0 0 24 24" fill="white"><path d="M20 6h-4V4c0-1.1-.9-2-2-2h-4c-1.1 0-2 .9-2 2v2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zM10 4h4v2h-4V4z"/></svg>';btn.title='电商助手';btn.style.cssText='position:fixed;bottom:100px;right:20px;width:56px;height:56px;background:linear-gradient(135deg,#e94560,#533483);border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;box-shadow:0 4px 20px rgba(233,69,96,.5);z-index:2147483647;';btn.onclick=function(){var d=capture();chrome.runtime.sendMessage({type:'CAPTURE_RESULT',data:d,platform:detect()});};document.body.appendChild(btn);}
  chrome.runtime.onMessage.addListener(function(msg,s,sendResponse){switch(msg.type){case'GET_PAGE_DATA':case'CAPTURE_PAGE':sendResponse({success:true,data:capture(),platform:detect()});break;case'FILL_FORM':sendResponse(fillForm(msg.data));break;default:sendResponse({error:'unknown'});}return true;});
  if(document.readyState==='complete')setTimeout(addBtn,500);else window.addEventListener('load',function(){setTimeout(addBtn,500);});
  console.log('[Content] 电商助手 v3.1 平台:',detect());
})();
